### ISSUE TITLE
Naming of this app

### ISSUE THREAD

**Issue by MorrisJobke** [nextcloud/workflow_script#1]
Is naming this files_ actually good? Because I also don't like files_texteditor - texteditor should be enough. And then naming it `files_external_*` is also not that good, because `files_external_*` is usually something like the dropbox or drive integration.

Could we change it to something like `execute_script` or something? Or `trigger_script`?

cc @nextcloud/designers for the creative part of naming things ;)

**Comment by MorrisJobke** [comment]
cc @blizzz

**Comment by MariusBluem** [comment]
workflow_script

**Comment by blizzz** [comment]
I do not have strong feelings about it, am very fine about renaming it. I like @MariusBluem's suggestion best. Let's gather some opinions and some time tomorrow I'll revise. After all, how to name things is the hardest problem in programming :)

**Comment by jancborchardt** [comment]
Agree with the whole `files_` prefixes being nonsense. "Workflow" is strange, and "execute" is ⚔💀🔫

How about something simple, descriptive and catchy like **📜 Scripting**?

**Comment by MorrisJobke** [comment]
> The good part about the disliked files_ prefix is that clarifies it is about files and nothing else.

Our whole product is about files 🙈

**Comment by blizzz** [comment]
> Our whole product is about files :see_no_evil: 

still you have several other components and various other apps on top :speak_no_evil:

**Comment by blizzz** [comment]
i'd like to resolve that finally. Please, until 2pm CET, speak out, the rest is silence.

If there's no reaction, I'll pick `external_scripting`. Sorry for the time pressure, however I don't think it is worth to waste too much time on it.

**Comment by blizzz** [comment]
already existing and released apps that make use of the workflow engine are

* files_accesscontrol
* files_autotagging

We won't change those.

Unrelease and thus still adjustable is `pdf_converter`

Mind, these are all app ids. Display names are a differnt thing and a currently:

* File access control
* Files automated tagging
* Automated PDF conversion
* Files against External Scripts

and can be changed anytime. Especially this one I'd also love to change to something more reasonable.

**Comment by jospoortvliet** [comment]
I'd call the pdf_converter workflow_pdf

In the UI, use "Workflow PDF Converter" and "Workflow external script" so somebody used to enterprise workflow tools recognizes the connection and purpose of these tools.

**Comment by blizzz** [comment]
`workflow_script` it is
