### ISSUE TITLE
workflow script access file metadata

### ISSUE THREAD

**Issue by psyciknz** [nextcloud/workflow_script#102]
Im investigating the use of a workflow script to move uploaded photos to some new locations.  i currently do it via a c# program...which is completely external to nextcloud and ru manually.

i had a loom a flows and wondered if i could use a nextcloud workflow to do the same task.

i see that nextcloud already seems to get exif information.  can workflow scripts get access to this information?  or do i implement via external script my own exif extractor?

then based on exif 
if camera model = "apple" move to folder x
else if camera model = "panasonic" move to folder y.

or am I barking completely up the wrong tree?

**Comment by blizzz** [comment]
> can workflow scripts get access to this information?

This app only provides an action, but not conditions. Implementing meta data conditions would have to be done in an app of its own.
