### ISSUE TITLE
Can't run python script

### ISSUE THREAD

**Issue by intervisionlord** [nextcloud/workflow_script#112]
## Steps to reproduce
1. Have a directory e.g. dirname1/uploads
2. Make workflow: file name match `/.*\/dirname1\/uploads\/.*/i` -> script: `python3 /path/to/script.py %n`
3. Create any file in dirname1/uploads

### Expected behaviour
Script triggered

### Actual behaviour
No reaction
manual executing python script works.

## Workflow Script app

**Workflow Script app version:** (see apps admin page: `/index.php/settings/apps`)
1.8.0

## Server configuration

**Operating system**: Debian 9

**Web server:** Apache + Nginx

**Database:** MySQL (mariadb)

**PHP version:** 7.4

**Nextcloud Version:**
23.0.2

**Where did you install Nextcloud from:**
github

**Comment by joshtrichards** [comment]
Hi @intervisionlord - I don't believe this is a bug. From my reading of the code, the FileName check matches on the basename not the full path - i.e.

https://en.wikipedia.org/wiki/Basename

You may be able to accomplish your use case by using the RequestURL check matcher instead.

**Comment by radoeka** [comment]
Is this still an issue?  If so, describe the current situation, if not the issue can be closed.

**Comment by intervisionlord** [comment]
I have removed this app, so i can't say if this behavior still persists or not.

**Comment by SprickW** [comment]
> Is this still an issue? If so, describe the current situation, if not the issue can be closed.

To me this is still an issue. If there is a way to define reaction on files created in a specifix directory ... I would like to know.

Nextcloud Hub 4 (26.0.5)

**Comment by radoeka** [comment]
Is a shell/bash working as expected?

What happens when you put the python3 command in the script itself?

Python script (/path/to/script.py):
```
#!/bin/python3
import module
print("This is python")
```

> Make workflow: file name match /.*\/dirname1\/uploads\/.*/i -> script: python3 /path/to/script.py %n

You can now make this: file name match /.*\/dirname1\/uploads\/.*/i -> script: /path/to/script.py %n

Or change it for bash:  file name match /.*\/dirname1\/uploads\/.*/i -> script: /path/to/script.sh %n

script.sh
```
#!/bin/bash

echo "$1" >> /var/tmp/nextcloud-test.dbg

```
