### ISSUE TITLE
Add Support for nextcloud 24

### ISSUE THREAD

**Issue by jakobroehrl** [nextcloud/workflow_script#115]
https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule

**Comment by tanju** [comment]
Most propably extension it self already supports nextcloud 24, nevertheless updateing nextcloud to 24 is blocked by "unsupported extension"

**Comment by mark3apps** [comment]
Any update on when this will be updated to support 24?  We rely on this for some of our automation and would really like to get it moving.

**Comment by spencerhughes** [comment]
This plugin is having issues that are blocking me from updating to 24. I can't seem to disable or remove it through the CLI or WebUI, and it re-enables itself after being disabled which prevents the 23 to 24 upgrade from completing. Any updates on when this will be updated for v.24?

**Comment by radoeka** [comment]
Any update on this issue.  See previous comment the workflow script seems to work fine on nc24.
Is it possible to provide the reason, what is preventing that this app is made to work with nc24?

**Comment by level420** [comment]
@nickvergessen it seems that everything is in place: https://github.com/nextcloud/workflow_script/commit/4f124c9690aa867aff0f4b63797a3e28cec3482d
Why is this not released?

**Comment by nickvergessen** [comment]
I don't know, I'm not the maintainer.
I'm just executing a script doing those changes in repositories where the author agreed: https://github.com/nextcloud/server/issues/27652

**Comment by blizzz** [comment]
v1.9.0 is released for 24, thanks for the patience.
