### ISSUE TITLE
NC 24.x to 25.0.2,25.0.3,25.0.4

### ISSUE THREAD

**Issue by AuchMarkus** [nextcloud/workflow_script#139]
## Steps to reproduce
1. work flow run script
2.if tag was assigned
3.select a tag

### Expected behaviour
if tag is set the script run

### Actual behaviour
**tag settings is gone after update from 24.x to 25.x** for some reason
**if i select a tag and save, if me open workflow again my tag is not shown**
means the script can not executed.

## Workflow Script app
that happens at run script and also auto tag files

**Workflow Script app version:** (see apps admin page: `/index.php/settings/apps`)
1.10.0

## Server configuration

**Operating system**: Ubuntu/RedHat/...

**Web server:** Apache/Nginx

**Database:** MySQL/Maria/SQLite/PostgreSQL

**PHP version:**

**Nextcloud Version:** (see admin page)
25.0.2

**Where did you install Nextcloud from:**

**Signing status:**

```
Login as admin user into your Nextcloud and access
http://example.com/index.php/settings/integrity/failed <- does not work with our domain name
paste the results here.
```

**List of activated apps:**

<details>
```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your server installation folder
```
</details>

**Nextcloud configuration:**

<details>
```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder

or

Insert your config.php content here
Make sure to remove all sensitive content such as passwords. (e.g. database password, passwordsalt, secret, smtp password, …)
```
</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...

**Are you using encryption:** yes/no

### Server log (data/nextcloud.log)
<details>
```
Insert your server log here
```
</details>

**Comment by AuchMarkus** [comment]
here i uploaded 2 screenshots
https://help.nextcloud.com/t/issue-with-workflow-tag-settings-after-upgrade-from-24-x-to-25-0-1-25-0-2/153410/1

**Comment by blizzz** [comment]
The title is confusing…

Anyway, this is a bug in server, and should be resolved by https://github.com/nextcloud/server/pull/36866. Backport to NC 25 still pending.

**Comment by AuchMarkus** [comment]
@blizzz 
thank you very much for this information.
regards
