### ISSUE TITLE
Adding a watermark to PDF files in Nextcloud

### ISSUE THREAD

**Issue by fernandovax20** [nextcloud/workflow_script#153]
Dear Nextcloud Workflow external scripts contributors,

I am writing to request your assistance in implementing a watermark on the PDF files downloaded from my Nextcloud instance. I would like all PDF files downloaded from my Nextcloud to have a watermark of my organization to protect our documents.

I have attempted to find a solution using Nextcloud's external workflows, but I have not found a way to implement the watermark on the downloaded PDF files. Therefore, I would like to inquire if there is any way to do this using the Workflow external scripts in Nextcloud.

If possible, could you provide me an example of how to add a watermark to PDF files using a Bash script in Nextcloud's Workflow external scripts?

Any help you can provide will be greatly appreciated. Thank you in advance!

Best regards,

Fernando Alvarez

**Comment by joshtrichards** [comment]
Hi @fernandovax20:

This a channel for submitting bugs and enhancement reports to the developers about the software itself. Unfortunately, this isn't a general support forum.

Your query would be better suited for the [Nextcloud Help Forum](https://help.nextcloud.com).
