### ISSUE TITLE
placeholder %i is not replaced because of wrong replacement of %s

### ISSUE THREAD

**Issue by pesfronau** [nextcloud/workflow_script#156]
## Steps to reproduce
1. put i% in script definition
### Expected behaviour
i% should be replaced with file id
### Actual behaviour
i% is not replaced
## Workflow Script app
1.11.0 until 1.12.0

there is a wrong replacement in Sourcecode of
/lib/Operation.php line 219
searching for placehoder %i and replace placeholder %s
so %i is never replaced
That is wrong since 1.11.0. Please fix

if (strpos($command, '%i')) {
			$nodeID = -1;
			try {
				$nodeID = $node->getId();
			} catch (InvalidPathException | NotFoundException $e) {
			}
			$command = str_replace('%s', escapeshellarg((string)$nodeID), $command);
		}

**Comment by cchartmann** [comment]
Hab mal grad nen PR dazu gemacht
