### ISSUE TITLE
Missing/inconsistent user documentation

### ISSUE THREAD

**Issue by caco3** [nextcloud/workflow_script#23]
Version 1.1.0 lacks some user documentation:

-  Description in config is incomplete. It states "If you do not use any of the following placeholders", how ever there is no list of any placeholders (you will find them only in the https://github.com/nextcloud/workflow_script/blob/master/README.md
- The behaviour of a rules group without any rule is not explained (AFAIK => it applies to all files)
- A rule using a match seems to expect regex, how ever it should be explained further, preferably with examples.
- There should be more examples (more trivial ones)

**Comment by blizzz** [comment]
> A rule using a match seems to expect regex, how ever it should be explained further, preferably with examples.

That's not specific to script, but a reused component. We're reworking that all heavily for 18.

**Comment by blizzz** [comment]
that was done was in the server
