### ISSUE TITLE
Documentation wrong (no-parameter use case)

### ISSUE THREAD

**Issue by caco3** [nextcloud/workflow_script#24]
Version 1.1.0 has wrong behaviour documentation. It states:

>  If you do not use any of the following placeholders, the file path will be added to the provided command. 

How ever this is not true! No parameter is appended!

**Comment by blizzz** [comment]
Do you mind correcting the text and open a PR?

**Comment by caco3** [comment]
@blizzz I am happy to create an MR, how ever I have some issues on doing this...

My NC tells me that the app is in version 1.2, how ever when I look on the `appinfo/info.xml`, it tells me, it is in version `1.7`:

```<?xml version="1.0"?>
<info xmlns:xsi= "http://www.w3.org/2001/XMLSchema-instance"
	  xsi:noNamespaceSchemaLocation="https://apps.nextcloud.com/schema/apps/info.xsd">
	<id>workflowengine</id>
	<name>Files workflow engine</name>
	<summary>Files workflow engine</summary>
	<description>Files workflow engine</description>
	<version>1.7.0</version>
	<licence>agpl</licence>
	<author>Morris Jobke</author>
	<namespace>WorkflowEngine</namespace>

	<types>
		<filesystem/>
	</types>

	<category>files</category>
	<website>https://github.com/nextcloud/server</website>
	<bugs>https://github.com/nextcloud/server/issues</bugs>
	<repository>https://github.com/nextcloud/server.git</repository>

	<dependencies>
		<nextcloud min-version="17" max-version="17"/>
	</dependencies>

	<settings>
		<admin-section>OCA\WorkflowEngine\Settings\Section</admin-section>
	</settings>
</info>
```

IIRC, I downloaded this version some weeks ago through the app store (from within NC)!

In its files I was unable to find the app description. AFAIK it is supposed to be in `lib/settings/Admin.php`, how ever that file is missing for me!

So I removed the files and downloaded `1.2` from github (as well as master `1.3`), how ever both versions lead to a server error 500 when I open the apps settings page!

**Comment by blizzz** [comment]
perhaps you have somewhere an app folder with a different name containing an old version? Just saw this today somewhere else with another app… there was a backup copy or something next to the regular folder.

**Comment by joshtrichards** [comment]
Hi @caco3: I believe you were looking at the `appinfo/info.xml` for the `workflowengine` app rather than the one for `workflow_script` plug-in app.

As to the original Issue: 

> If you do not use any of the following placeholders, the file path will be added to the provided command.

The docs (README at least) look it's correct these days, though I'm unable to find when this happened oddly:

> When no placeholder was specified, then the exact command as given is being executed.

I think we can close out this four year old Issue. :)
