### ISSUE TITLE
Request: Add way to trigger tasks for immediate action

### ISSUE THREAD

**Issue by caco3** [nextcloud/workflow_script#27]
The scheduled tasks will only be executed on the next cron run.

For testing it would be great if one could trigger it from within the web interface. Alternatively it should be documented how to do through a terminal (=> call cron.php)

**Comment by jcurl** [comment]
I just came across this to try and debug why my tests weren't working (I need to trigger a job immediately after an upload to post-process data). Then I changed the logging to DEBUG and noticed that it takes a long time before the cron is run (hour or so?).

As a workaround, is there a hint where in the sources I might be able to workaround this to trigger immediately? I'm not a PHP dev (but do develop in C for embedded), so some guidance would be appreciated.

As in the original request, it could be useful if there's a description how to trigger this from the command line (so I can put in my own cronjob).

**Comment by blizzz** [comment]
> Then I changed the logging to DEBUG and noticed that it takes a long time before the cron is run (hour or so?).

please see https://docs.nextcloud.com/server/latest/admin_manual/configuration_server/background_jobs_configuration.html

**Comment by blizzz** [comment]
> For testing it would be great if one could trigger it from within the web interface. 

You still need to force an event as configured to happen. Assumed it is there, hypothetically we can show a button to run an enqueued job perhaps. Alas it should be decoupled from the web request process for it might get in trouble on timeouts.

> Alternatively it should be documented how to do through a terminal (=> call cron.php)

That's fair and probably best to achieve as you likely be on the system anyway when setting up this flow/script.

**Comment by jcurl** [comment]
Thanks for the pointer to the server docs, I did find them too, and it does help them being here.

I've playing around how to get this to work. I set up the background jobs using 'cron' with systemd. It runs, and I can now see my scripts run (the md5sum is generated) also by setting the logging to DEBUG in the config file. Are there any limitations to what can be done in the script? The output of the script is next to the original file, and so it appears in the Files tab, I want to trigger "occ" to scan for files (works when done manually on the commandline), but for some reason, this doesn't appear to have any effect in the script itself.

e.g.

```sh
#
# Usage from NextCloud:
#  /opt/scripts/md5sum.sh %a %n

NEXTCLOUDDATA=/var/www/nextcloud/data
if [ ! -d $NEXTCLOUDDATA/$1 ]; then
        echo "USER $1 not found. Aborting" >> /tmp/mdlog.txt
        exit 1;
fi

if [ ! -f $NEXTCLOUDDATA/$2 ]; then
        echo "PATH $2 not found. Aborting" >> /tmp/mdlog.txt
        ls -l $NEXTCLOUDDATA >> /tmp/mdlog.txt
        ls -l $NEXTCLOUDDATA/$2 >> /tmp/mdlog.txt
        exit 1;
fi
echo "USER $1 PATH $2 execution" >> /tmp/mdlog.txt

INPUTFILE=$NEXTCLOUDDATA/$2
md5sum $INPUTFILE > $INPUTFILE.md5sum.txt
echo "Running Script Update" >> /tmp/mdlog.txt
ls -l $INPUTFILE* >> /tmp/mdlog.txt

/usr/bin/php -f /var/www/nextcloud/occ files:scan $1 >> /tmp/mdlog.txt
echo "DONE" >> /tmp/mdlog.txt
```

I don't see the "DONE" in the output (but everything else before the call to PHP)

Really appreciate your pointers.

**Comment by blizzz** [comment]
Works for me. Perhaps scanning takes too long for you?

You can only scan the new file, instead of everything, that should speed up things.

```bash
# ...
RELFILE="$2.md5sum.txt"
/usr/bin/php -f /srv/http/nextcloud/master/occ files:scan -p "$RELFILE" -- $1 >> /tmp/mdlog.txt
# ...
```

**Comment by blizzz** [comment]
As there is no feedback since a while I will close this ticket. If this is still happening please feel free to reopen.
