### ISSUE TITLE
[Feature Request] Data Request app integration

### ISSUE THREAD

**Issue by sunjam** [nextcloud/workflow_script#29]
[As filed here on the Data Request app](https://github.com/nextcloud/data_request/issues/32).  

![Screen Shot 2019-10-04 at 12 14 54 PM](https://user-images.githubusercontent.com/1787238/66238700-f3c44380-e6ac-11e9-86e3-836bd06aa4d0.png)

I noticed there is no way to automate a Data Request yet.  An option that could work down the line is [Workflow integration](https://github.com/nextcloud/workflow_script/), since it is [planned to be expanded in Nextcloud 18](https://nextcloud.com/blog/nextcloud-flow-makes-it-easy-to-automate-actions-and-workflows/) and beyond.

**Comment by blizzz** [comment]
certainly, but not within this app :) This is just another possible action working with the workflowengine.
