### ISSUE TITLE
suggestion: fallback to exec() instead of shell_exec() in restricted environments.

### ISSUE THREAD

**Issue by gloryknight** [nextcloud/workflow_script#34]
Please consider usind exec() instead of shell_exec() since it does not work in my environment. A configuration option should suffice.

## Steps to reproduce
1. Activate workflow_script in an environment where shell_exec() is not allowed.
2. Try to execute a script.
3. Nothing happens. No obvious error is reported.

### Expected behaviour
action should be executed.

### Actual behaviour
**Error is generated in the logs:**
Error | PHP | shell_exec() has been disabled for security reasons at /web/htdocs/www.huugl.eu/home/nc/apps/serverinfo/lib/OperatingSystems/DefaultOs.php#96
-- | -- | --

## Workflow Script app

**Workflow Script app version:1.2.0

## Server configuration
**Operating system**: Linux
**Web server:** Apache
**Database:** MySQL
**PHP version:7.2.2
**Nextcloud Version:17.0.2

**Where did you install Nextcloud from:** official download

**Signing status:**

```
No errors have been found.
```

**Are you using external storage, if yes which one:** no

**Are you using encryption:** no

### Server log (data/nextcloud.log)
<details>
```

Error | PHP | shell_exec() has been disabled for security reasons at /web/htdocs/www.huugl.eu/home/nc/apps/serverinfo/lib/OperatingSystems/DefaultOs.php#96 |   | 2020-01-19T22:38:16+0100
-- | -- | -- | -- | --
Error | PHP | shell_exec() has been disabled for security reasons at /web/htdocs/www.huugl.eu/home/nc/apps/serverinfo/lib/OperatingSystems/DefaultOs.php#95 |   | 2020-01-19T22:38:16+0100
Error | PHP | shell_exec() has been disabled for security reasons at /web/htdocs/www.huugl.eu/home/nc/apps/serverinfo/lib/OperatingSystems/DefaultOs.php#87 |   | 2020-01-19T22:38:16+0100
Error | PHP | shell_exec() has been disabled for security reasons at /web/htdocs/www.huugl.eu/home/nc/apps/serverinfo/lib/OperatingSystems/DefaultOs.php#79 |   | 2020-01-19T22:38:16+0100
```
</details>

**Comment by joshtrichards** [comment]
It seems pretty unusual to have a restricted environment with`shell_exec()` disabled while leaving `exec()` enabled. I can't even... think of a good reason to do that. Usually it'd be both or none.

Also, I'm confused because that log output is all from the `serverinfo` app. Though a similar message should be getting logged for `workflow_script`. Are/were you not seeing one from this app?

**Comment by gloryknight** [comment]
This is an old ticket. I've been using a PHP only hosting. Since than I've changed to a VPS hosting and do not observe this behavior. Since nobody else reports this bug it would be fine with me to close the issue. Thank you.
