### ISSUE TITLE
Workflow only runs without rules

### ISSUE THREAD

**Issue by fvzwieten** [nextcloud/workflow_script#37]
## Steps to reproduce
1. Create an external script that does "logger %e %n" without any rules -> it logs
2. Add a rule, any rule. It stops working
3.

### Expected behaviour
It should process the rules and when it has a positive, it should fire.

### Actual behaviour
I tried the following:
filename match /^img-[0-9]{8}-wa[0-9]{4}.jpe?g$/i (this one works flawlessly with automatic tagging)
file system tag is tagged with whatsapp (the tagging itself, based on above rule, works).

## Workflow Script app

**Workflow Script app version:** (see apps admin page: `/index.php/settings/apps`)
1.2.0

nextcloud 17.0.2, nginx, php7.3-fpm, redis on raspbian 10 on rpi4.

**Comment by Pingger** [comment]
> /^img-[0-9]{8}-wa[0-9]{4}.jpe?g$/i

I might be mistaken, but my guess is, that `^` is the issue.

**Comment by blizzz** [comment]
As there is no feedback since a while I will close this ticket. If this is still happening please feel free to reopen.
