### ISSUE TITLE
External script does not work on files in group folders.

### ISSUE THREAD

**Issue by ernolf** [nextcloud/workflow_script#38]
Everything said by title.

**Comment by jonas154** [comment]
having the same problem. I think the issue occurs when:

User A shares a folder with User B. When User B uploads now a file, %n gives its relative upload path (but not the path to the file itself as it is under the path of user A)

**Comment by jurgenhaas** [comment]
Same issue here.

**Comment by k1l1** [comment]
Duplicate of #48

**Comment by Pingger** [comment]
> 
> 
> Duplicate of #48

No. Shared folders do trigger workflow scripts. 

**GROUP FOLDERS DON'T EVEN TRIGGER**. Your "workaround" does not even remotely solve this.

So again to be clear: Not a duplicate

**Comment by k1l1** [comment]
Ok, then its a different story there.

**Comment by ostasevych** [comment]
Hi! So, are any news on group folders?

**Comment by Nils160988** [comment]
Changes in group folders do trigger flows for me (NC 27.1.3), so I would expect this issue to be resolved here. Can someone comment if this issue is still valid?

**Comment by ostasevych** [comment]
> Changes in group folders do trigger flows for me (NC 27.1.3), so I would expect this issue to be resolved here. Can someone comment if this issue is still valid?

Still valid.

**Comment by blizzz** [comment]
Proposed fix in #218
