### ISSUE TITLE
Flow with external script stopped working (The configuration is invalid)

### ISSUE THREAD

**Issue by caco3** [nextcloud/workflow_script#39]
### Steps to reproduce
1. Create a flow with `Run Script`
2. Add any condition to it
3. Add a run script, eg. `true`
4. Press the save button

### Expected behaviour
The button changes to `active`

### Actual behaviour
The button changes to `The configuration is invalid`

## Server configuration detail

**Operating system:** Linux 4.4.59+ #24922 SMP PREEMPT Mon Aug 19 12:13:37 CST 2019 x86_64

**Webserver:** Apache/2.4.38 (Debian) (apache2handler)

**Database:** mysql 10.3.21

**PHP version:** 

7.3.14
Modules loaded: Core, date, libxml, openssl, pcre, sqlite3, zlib, ctype, curl, dom, fileinfo, filter, ftp, hash, iconv, json, mbstring, SPL, PDO, session, posix, Reflection, standard, SimpleXML, pdo_sqlite, Phar, tokenizer, xml, xmlreader, xmlwriter, mysqlnd, apache2handler, apcu, exif, gd, gmp, imagick, intl, ldap, memcached, pcntl, pdo_mysql, pdo_pgsql, redis, sodium, zip, Zend OPcache

**Nextcloud version:** 18.0.0 - 18.0.0.10

**Updated from an older Nextcloud/ownCloud or fresh install:** Latest docker container

**Where did you install Nextcloud from:** Docker container

<details><summary>Signing status</summary>

Array
(
)

</details>

<details><summary>List of activated apps</summary>

```
Enabled:
 - accessibility: 1.4.0
 - activity: 2.11.0
 - cloud_federation_api: 1.1.0
 - comments: 1.8.0
 - dav: 1.14.0
 - federatedfilesharing: 1.8.0
 - federation: 1.8.0
 - files: 1.13.1
 - files_pdfviewer: 1.7.0
 - files_rightclick: 0.15.2
 - files_sharing: 1.10.1
 - files_trashbin: 1.8.0
 - files_versions: 1.11.0
 - files_videoplayer: 1.7.0
 - firstrunwizard: 2.7.0
 - issuetemplate: 0.6.0
 - keeweb: 0.6.1
 - logreader: 2.3.0
 - lookup_server_connector: 1.6.0
 - nextcloud_announcements: 1.7.0
 - notifications: 2.6.0
 - oauth2: 1.6.0
 - password_policy: 1.8.0
 - photos: 1.0.0
 - privacy: 1.2.0
 - provisioning_api: 1.8.0
 - ransomware_protection: 1.6.0
 - recommendations: 0.6.0
 - serverinfo: 1.8.0
 - settings: 1.0.0
 - sharebymail: 1.8.0
 - support: 1.1.0
 - survey_client: 1.6.0
 - systemtags: 1.8.0
 - text: 2.0.0
 - theming: 1.9.0
 - twofactor_backupcodes: 1.7.0
 - updatenotification: 1.8.0
 - viewer: 1.2.0
 - workflow_script: 1.3.1
 - workflowengine: 2.0.0
Disabled:
 - admin_audit
 - bruteforcesettings
 - encryption
 - files_external
 - files_fulltextsearch
 - fulltextsearch
 - onlyoffice
 - user_ldap

```
</details>

<details><summary>Configuration (config/config.php)</summary>

```
{
    "htaccess.RewriteBase": "\/",
    "memcache.local": "\\OC\\Memcache\\APCu",
    "apps_paths": [
        {
            "path": "\/var\/www\/html\/apps",
            "url": "\/apps",
            "writable": false
        },
        {
            "path": "\/var\/www\/html\/custom_apps",
            "url": "\/custom_apps",
            "writable": true
        }
    ],
    "instanceid": "***REMOVED SENSITIVE VALUE***",
    "passwordsalt": "***REMOVED SENSITIVE VALUE***",
    "secret": "***REMOVED SENSITIVE VALUE***",
    "trusted_domains": [
 **REMOVED SENSITIVE VALUE***
    ],
    "datadirectory": "***REMOVED SENSITIVE VALUE***",
    "dbtype": "mysql",
    "version": "18.0.0.10",
    "overwrite.cli.url": "**REMOVED SENSITIVE VALUE***",
    "overwriteprotocol": "https",
    "dbname": "***REMOVED SENSITIVE VALUE***",
    "dbhost": "***REMOVED SENSITIVE VALUE***",
    "dbport": "",
    "dbtableprefix": "oc_",
    "mysql.utf8mb4": true,
    "dbuser": "***REMOVED SENSITIVE VALUE***",
    "dbpassword": "***REMOVED SENSITIVE VALUE***",
    "installed": true,
    "loglevel": 2,
    "maintenance": false,
    "theme": "",
    "app_install_overwrite": [
        "dscrenamer",
        "onlyoffice",
        "keeweb"
    ]
}
```
</details>

**Are you using external storage, if yes which one:** no

**Are you using encryption:** 

**Are you using an external user-backend, if yes which one:** no

## Client configuration

**Browser:** Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:72.0) Gecko/20100101 Firefox/72.0

**Operating system:** Ubuntu

## Logs

<details><summary>Web server error log</summary>

```
-
```
</details>

<details><summary>Nextcloud log</summary>

```
no log entry related to this issue
```
</details>

<details><summary>Browser log</summary>

-
</details>

**Comment by caco3** [comment]
![grafik](https://user-images.githubusercontent.com/1783586/74383204-0edb5880-4def-11ea-8994-611e94f0581b.png)

**Comment by caco3** [comment]
The flows I have worked well until they stopped working end of January. My Docker container gets updated automatically, so maybe there was a regression?

**Comment by caco3** [comment]
To reproduce it:

1. Grab the latest docker container from https://registry.hub.docker.com/_/nextcloud/ and set it up
1. Install the `Workflow external scripts`. I had it in version `1.3.1`
1. Try to create a flow with it.

I tried several commands, but they all end up with `The configuration is invalid`:
 * `true`
 * `echo %i`
 * `ls`
 * `/bin/true`

@blizzz  @juliushaertl Please give some advice

**Comment by caco3** [comment]
So after deeply digging into the code, namely `Rule.vue`, I found out that the text `No events are chosen` **under** the error message **actually** are part of the error message...

Now, since the rules worked before, I didn't expect that they suddenly miss data and stop working without any notification! It would be much easier for users, if the problematic field somehow would get highlighted!

My next step normally would be to create a follow-up feature request. How ever since on nextcloud the devs don't care for them, I think it would be a waste of time :(

**Comment by juliushaertl** [comment]
> My next step normally would be to create a follow-up feature request. How ever since on nextcloud the devs don't care for them, I think it would be a waste of time :(

@caco3  That would still be appreciated. Please don't make assumptions like that just based on a delayed reply. My github notification backlog is quite big, so please understand that it sometimes just takes a while until we get to see that message and reply to it.

**Comment by juliushaertl** [comment]
Regarding the actual issue, it is true that we generally don't allow flow rules without an event unless they have their own event handling implemented like files_accesscontrol. But we should look into that at the server repo.

**Comment by caco3** [comment]
> That would still be appreciated. Please don't make assumptions like that just based on a delayed reply. 

https://github.com/nextcloud/updater/issues/158#issuecomment-399216799 sadly proves different :(

The issue still exists and no dev was willing to support tracing the issue further down.

**Comment by ho1ger** [comment]
Has this bug been fixed at any point? Because I just try to set up a workflow and get the error "The configuration is invalid" - I use version 26.0.2.
