### ISSUE TITLE
Unable to create new "Run script" flow - Nextcloud 18

### ISSUE THREAD

**Issue by blaynec** [nextcloud/workflow_script#40]
### Steps to reproduce
1. Login to Nextcloud instance
2. Navigate to:  https://MyNextCloudInstance.com/index.php/settings/admin/workflow
3. Click "Add new flow" in the "Run script" flow.
4. Choose selection criteria: "File MIME type" is "text/plain"
5. Enter script to run: "/usr/bin/test.sh %f"
6. Click "Save"

### Expected behaviour
I would expect the app to create a new flow.

### Actual behaviour
What happens is the Save button turns dark yellow and says, "X  The configuration is invalid".  Below the button it says, "No events are chosen."

## Server configuration detail

**Operating system:** Linux 4.19.0-8-amd64 #1 SMP Debian 4.19.98-1 (2020-01-26) x86_64

**Webserver:** Apache/2.4.38 (Debian) (apache2handler)

**Database:** mysql 10.3.22

**PHP version:** 

7.3.14-1~deb10u1
Modules loaded: Core, date, libxml, openssl, pcre, zlib, filter, hash, Reflection, SPL, session, sodium, standard, apache2handler, mysqlnd, PDO, xml, calendar, ctype, curl, dom, mbstring, fileinfo, ftp, gd, gettext, gmp, iconv, imagick, intl, json, exif, mysqli, pdo_mysql, Phar, posix, readline, shmop, SimpleXML, sockets, sysvmsg, sysvsem, sysvshm, tokenizer, wddx, xmlreader, xmlwriter, xsl, zip, Zend OPcache

**Nextcloud version:** 18.0.1 - 18.0.1.3

**Updated from an older Nextcloud/ownCloud or fresh install:** Updated from Nextcloud version 17.?

**Where did you install Nextcloud from:** Original install was Jan 2020 - version 17.x

<details><summary>Signing status</summary>

Array
(
)

</details>

<details><summary>List of activated apps</summary>

```
Enabled:
 - accessibility: 1.4.0
 - activity: 2.11.0
 - admin_audit: 1.8.0
 - apporder: 0.9.0
 - bookmarks: 2.3.4
 - cloud_federation_api: 1.1.0
 - cms_pico: 1.0.5
 - comments: 1.8.0
 - cookbook: 0.5.7
 - cospend: 0.3.2
 - dav: 1.14.0
 - federatedfilesharing: 1.8.0
 - files: 1.13.1
 - files_automatedtagging: 1.8.0
 - files_pdfviewer: 1.7.0
 - files_retention: 1.7.0
 - files_rightclick: 0.15.2
 - files_sharing: 1.10.1
 - files_trashbin: 1.8.0
 - files_versions: 1.11.0
 - files_videoplayer: 1.7.0
 - firstrunwizard: 2.7.0
 - issuetemplate: 0.6.0
 - logreader: 2.3.0
 - lookup_server_connector: 1.6.0
 - metadata: 0.11.1
 - nextcloud_announcements: 1.7.0
 - notes: 3.1.5
 - notifications: 2.6.0
 - oauth2: 1.6.0
 - password_policy: 1.8.0
 - photos: 1.0.0
 - provisioning_api: 1.8.0
 - recommendations: 0.6.0
 - serverinfo: 1.8.0
 - settings: 1.0.0
 - sharebymail: 1.8.0
 - support: 1.1.0
 - suspicious_login: 3.1.0
 - systemtags: 1.8.0
 - theming: 1.9.0
 - twofactor_backupcodes: 1.7.0
 - twofactor_totp: 4.1.2
 - updatenotification: 1.8.0
 - video_converter: 0.1.3
 - viewer: 1.2.0
 - workflow_pdf_converter: 1.3.1
 - workflow_script: 1.3.1
 - workflowengine: 2.0.0
Disabled:
 - analytics
 - encryption
 - federation
 - files_accesscontrol
 - files_external
 - privacy
 - survey_client
 - text
 - user_ldap

```
</details>

<details><summary>Configuration (config/config.php)</summary>

```
{
    "instanceid": "***REMOVED SENSITIVE VALUE***",
    "passwordsalt": "***REMOVED SENSITIVE VALUE***",
    "secret": "***REMOVED SENSITIVE VALUE***",
    "trusted_domains": [
        "192.168.x.x",
        "myURL.com",
    ],
    "datadirectory": "***REMOVED SENSITIVE VALUE***",
    "dbtype": "mysql",
    "version": "18.0.1.3",
    "overwrite.cli.url": "http:\/\/myURL.com\/nextcloud",
    "dbname": "***REMOVED SENSITIVE VALUE***",
    "dbhost": "***REMOVED SENSITIVE VALUE***",
    "dbport": "",
    "dbtableprefix": "oc_",
    "mysql.utf8mb4": true,
    "dbuser": "***REMOVED SENSITIVE VALUE***",
    "dbpassword": "***REMOVED SENSITIVE VALUE***",
    "installed": true,
    "maintenance": false,
    "mail_from_address": "***REMOVED SENSITIVE VALUE***",
    "mail_smtpmode": "smtp",
    "mail_sendmailmode": "smtp",
    "mail_domain": "***REMOVED SENSITIVE VALUE***",
    "mail_smtpauthtype": "LOGIN",
    "mail_smtpauth": 1,
    "mail_smtpsecure": "ssl",
    "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
    "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
    "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
    "mail_smtpport": "465",
    "theme": "",
    "loglevel": 2,
    "updater.release.channel": "stable"
}
```
</details>

**Are you using external storage, if yes which one:** no

**Are you using encryption:** 

**Are you using an external user-backend, if yes which one:** no

## Client configuration

**Browser:** Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:73.0) Gecko/20100101 Firefox/73.0

**Operating system:** 

## Logs

<details><summary>Web server error log</summary>

```
I don't think this is related to this issue - but I suppose it could be.  I did find this line in my web server error log.  It was only listed once in the error log (/var/log/apache2/error.log):

[Tue Feb 18 11:31:41.776200 2020] [php7:warn] [pid 25286] [client x.x.x.x:35626] PHP Warning:  "continue" targeting switch is equivalent to "break". Did you mean to use "continue 2"? in /var/www/html/nextcloud/apps/workflowengine/lib/Helper/LogContext.php on line 55

```
</details>

<details><summary>Nextcloud log</summary>

```

```
</details>

<details><summary>Browser log</summary>

</details>

![RunScript_Error](https://user-images.githubusercontent.com/35807800/74768833-802f6700-5246-11ea-9059-c308ce415842.png)

**Comment by caco3** [comment]
Same issue as I had in https://github.com/nextcloud/workflow_script/issues/39

You have to select an event!

**Comment by blaynec** [comment]
"You have to select an event"

How do I select an event.  I'm not sure what this means.  I assumed the "Run script" box was the event I wanted to happen.  It appears that I'm missing something.  
Can you help me understand how to select an event?

**Comment by blaynec** [comment]
OH!  I think I found it.

Next to the "When" it says "Select option".  You need to click on the "Select option" before you can create the flow.  Thanks for help help in directing me to something that should have been more obvious.  Attached is a screen shot that might help someone else in the future.
![Fix-SelectEvent](https://user-images.githubusercontent.com/35807800/74776040-161dbe80-5254-11ea-9b7e-1850d15a2d1c.png)

**Comment by caco3** [comment]
You are welcome!
Sorry I wasn't clearer :(

**Comment by blaynec** [comment]
caco3, thanks for your help!  I think I wrote my response weird.  What I meant was that it should have been more obvious to me.  I just missed something that was right there on the page.
