### ISSUE TITLE
getPath() on null - undefined variable in Operation.php

### ISSUE THREAD

**Issue by martingwb** [nextcloud/workflow_script#42]
## Steps to reproduce
1. rename or move a file
2. error message is displayed

### Expected behaviour
renaming/moving the file without an error message

### Actual behaviour
Message popup (top right corner) is displayed saying " Cannot move <filename>" or "Cannot rename <filename>".
Error messages in the logging app:

[remote] Error: Error: Call to a member function getPath() on null at <<closure>>

 0. /var/www/nextcloud/apps/workflowengine/lib/AppInfo/Application.php line 114
    OCA\WorkflowScript\Operation->onEvent("*** sensitive parameter replaced ***", "*** sensitive parameter replaced ***", OCA\WorkflowEngine\Service\RuleMatcher {})
 1. /var/www/nextcloud/3rdparty/symfony/event-dispatcher/EventDispatcher.php line 247
    OCA\WorkflowEngine\AppInfo\Application->OCA\WorkflowEngine\AppInfo\{closure}("*** sensitive parameters replaced ***")
 2. /var/www/nextcloud/3rdparty/symfony/event-dispatcher/EventDispatcher.php line 73
    Symfony\Component\EventDispatcher\EventDispatcher->callListeners([Closure {}], "*** sensitive parameter replaced ***", "*** sensitive parameter replaced ***")
 3. /var/www/nextcloud/lib/private/EventDispatcher/EventDispatcher.php line 80
    Symfony\Component\EventDispatcher\EventDispatcher->dispatch("*** sensitive parameter replaced ***", "*** sensitive parameter replaced ***")
 4. /var/www/nextcloud/lib/private/EventDispatcher/SymfonyAdapter.php line 63
    OC\EventDispatcher\EventDispatcher->dispatch("*** sensitive parameter replaced ***", "*** sensitive parameter replaced ***")
 5. /var/www/nextcloud/lib/private/Files/Node/HookConnector.php line 147
    OC\EventDispatcher\SymfonyAdapter->dispatch("*** sensitive parameter replaced ***", "*** sensitive parameter replaced ***")
 6. /var/www/nextcloud/lib/private/legacy/hook.php line 111
    OC\Files\Node\HookConnector->postRename({oldpath: "/Doku ... "})
 7. /var/www/nextcloud/lib/private/Files/View.php line 849
    OC_Hook::emit("OC_Filesystem", "post_rename", {oldpath: "/Doku ... "})
 8. /var/www/nextcloud/apps/dav/lib/Connector/Sabre/Directory.php line 440
    OC\Files\View->rename("/Dokumente/test2.md", "/Dokumente/Dokumente/test2.md")
 9. /var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Tree.php line 158
    OCA\DAV\Connector\Sabre\Directory->moveInto("test2.md", "files/martin/Dokumente/test2.md", OCA\DAV\Connector\Sabre\File {})
10. /var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/CorePlugin.php line 642
    Sabre\DAV\Tree->move("files/martin/Dokumente/test2.md", "files/martin/Do ... d")
11. <<closure>>
    Sabre\DAV\CorePlugin->httpMove(Sabre\HTTP\Reque ... "}, Sabre\HTTP\Response {})
12. /var/www/nextcloud/3rdparty/sabre/event/lib/EventEmitterTrait.php line 105
    call_user_func_array([Sabre\DAV\CorePlugin {},"httpMove"], [Sabre\HTTP\Requ ... }])
13. /var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php line 479
    Sabre\Event\EventEmitter->emit("method:MOVE", [Sabre\HTTP\Requ ... }])
14. /var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php line 254
    Sabre\DAV\Server->invokeMethod(Sabre\HTTP\Reque ... "}, Sabre\HTTP\Response {})
15. /var/www/nextcloud/apps/dav/lib/Server.php line 319
    Sabre\DAV\Server->exec()
16. /var/www/nextcloud/apps/dav/appinfo/v2/remote.php line 35
    OCA\DAV\Server->exec()
17. /var/www/nextcloud/remote.php line 165
    require_once("/var/www/nextcl ... p")

[PHP] Error: Undefined variable: node at /var/www/nextcloud/apps/workflow_script/lib/Operation.php#203

MOVE /remote.php/dav/files/<user>/Dokumente/Neues%20Textdokument2.md
from 10.0.0.33 by <user> at 2020-03-04T07:21:01+00:00

## Workflow Script app
1.3.1

## Server configuration
**Operating system**: Ubuntu/RedHat/...
Linux 4.19.97-v7l+ #1294 SMP Thu Jan 30 13:21:14 GMT 2020 armv7l

**Web server:** Apache/Nginx
Apache (fpm-fcgi)

**Database:** MySQL/Maria/SQLite/PostgreSQL
mysql 10.3.15

**PHP version:**
7.3.4-2
Modules loaded: Core, date, libxml, openssl, pcre, zlib, filter, hash, Reflection, SPL, session, sodium, standard, cgi-fcgi, mysqlnd, PDO, xml, bz2, calendar, ctype, curl, dom, mbstring, fileinfo, ftp, gd, gettext, gmp, iconv, igbinary, imagick, intl, json, ldap, exif, mysqli, pdo_mysql, Phar, posix, readline, redis, shmop, SimpleXML, smbclient, sockets, sysvmsg, sysvsem, sysvshm, tokenizer, wddx, xmlreader, xmlwriter, xsl, zip, libsmbclient, Zend OPcache

**Nextcloud Version:** (see admin page)
18.0.1 - 18.0.1.3

**Where did you install Nextcloud from:**
nextcloudpi

**Signing status:**
Array
(
    [user_external] => Array
        (
            [INVALID_HASH] => Array
                (
                    [appinfo/info.xml] => Array
                        (
                            [expected] => 06b250c3a2c2ae01c8a2c4b963d6449c99645dca36ee197c3aa513fb7ac3e90e42dc1408ee6957408d85f9f9a973b8983719e9c15125d42211d43f0853c7bf75
                            [current] => e5da848ca44b3b60abb1c99a3d26455d78464f94ea1f5f522b07d642096a771dcde9a1a5289e271805292659edc42925a86b5d6ad22ffa98b79ecec5bfed69ff
                        )

                    [lib/smb.php] => Array
                        (
                            [expected] => 283a99667fd865e54423d575953423bc6e15862b7683885cb5675aafdb3b2cbc1400a1318ec81cdbd90ce827c3f839aa6daf6a0f6e3ac6bd2742947498dd14f9
                            [current] => 1c12005d92f88017564fb4135a532810aab33ffab22eac67c19501a59d213518e417cceb83f5e9ea4b448ea81fff3149da37eefb0100a61bce3140ce67f8decc
                        )

                )

        )

)

**List of activated apps:**

 - accessibility: 1.4.0
 - activity: 2.11.0
 - admin_audit: 1.8.0
 - apporder: 0.9.0
 - calendar: 2.0.2
 - cloud_federation_api: 1.1.0
 - cms_pico: 1.0.5
 - comments: 1.8.0
 - contacts: 3.2.0
 - dav: 1.14.0
 - deck: 0.8.0
 - external: 3.5.0
 - federatedfilesharing: 1.8.0
 - federation: 1.8.0
 - files: 1.13.1
 - files_external: 1.9.0
 - files_external_gdrive: 0.4.0
 - files_external_onedrive: 1.0.7
 - files_fulltextsearch: 1.4.1
 - files_markdown: 2.2.0
 - files_mindmap: 0.0.17
 - files_pdfviewer: 1.7.0
 - files_rightclick: 0.15.2
 - files_sharing: 1.10.1
 - files_trackdownloads: 1.7.0
 - files_trashbin: 1.8.0
 - files_versions: 1.11.0
 - files_videoplayer: 1.7.0
 - firstrunwizard: 2.7.0
 - fulltextsearch: 1.4.1
 - fulltextsearch_elasticsearch: 1.5.0
 - issuetemplate: 0.6.0
 - keeweb: 0.6.2
 - logreader: 2.3.0
 - lookup_server_connector: 1.6.0
 - maps: 0.1.5
 - metadata: 0.11.1
 - music: 0.13.0
 - news: 14.1.3
 - nextcloud_announcements: 1.7.0
 - nextcloudpi: 0.0.1
 - notes: 3.1.5
 - notifications: 2.6.0
 - oauth2: 1.6.0
 - occweb: 0.0.7
 - password_policy: 1.8.0
 - photos: 1.0.0
 - previewgenerator: 2.2.0
 - privacy: 1.2.0
 - provisioning_api: 1.8.0
 - recommendations: 0.6.0
 - serverinfo: 1.8.0
 - settings: 1.0.0
 - sharebymail: 1.8.0
 - socialsharing_diaspora: 2.0.0
 - spreed: 8.0.5
 - support: 1.1.0
 - survey_client: 1.6.0
 - systemtags: 1.8.0
 - talk_simple_poll: 1.1.0
 - tasks: 0.11.3
 - text: 2.0.0
 - theming: 1.9.0
 - twofactor_backupcodes: 1.7.0
 - unsplash: 1.1.5
 - updatenotification: 1.8.0
 - user_external: 0.8.0
 - user_ldap: 1.8.0
 - viewer: 1.2.0
 - workflow_script: 1.3.1
 - workflowengine: 2.0.0
Disabled:
 - encryption
 - gallery
 - ocr
 - previewgenerator.orig
 - social

**Nextcloud configuration:**

{
    "passwordsalt": "***REMOVED SENSITIVE VALUE***",
    "secret": "***REMOVED SENSITIVE VALUE***",
    "trusted_domains": {
        "0": "localhost",
        "5": "nextcloudpi.local",
        "7": "nextcloudpi",
        "8": "nextcloudpi.lan",
        "1": "10.0.0.15",
        "2": "10.0.0.16"
 ...
    },
    "datadirectory": "***REMOVED SENSITIVE VALUE***",
    "dbtype": "mysql",
    "version": "18.0.1.3",
    "overwrite.cli.url": "https:\/\/mgwb-nc.crabdance.com\/",
    "dbname": "***REMOVED SENSITIVE VALUE***",
    "dbhost": "***REMOVED SENSITIVE VALUE***",
    "dbport": "",
    "dbtableprefix": "oc_",
    "mysql.utf8mb4": true,
    "dbuser": "***REMOVED SENSITIVE VALUE***",
    "dbpassword": "***REMOVED SENSITIVE VALUE***",
    "installed": true,
    "instanceid": "***REMOVED SENSITIVE VALUE***",
    "memcache.local": "\\OC\\Memcache\\Redis",
    "memcache.locking": "\\OC\\Memcache\\Redis",
    "redis": {
        "host": "***REMOVED SENSITIVE VALUE***",
        "port": 0,
        "timeout": 0,
        "password": "***REMOVED SENSITIVE VALUE***"
    },
    "tempdirectory": "\/media\/USBdrive\/ncdata\/tmp",
    "mail_smtpmode": "smtp",
    "mail_smtpauthtype": "LOGIN",
    "mail_from_address": "***REMOVED SENSITIVE VALUE***",
    "mail_domain": "***REMOVED SENSITIVE VALUE***",
    "preview_max_x": "2048",
    "preview_max_y": "2048",
    "jpeg_quality": "60",
    "overwriteprotocol": "https",
    "maintenance": false,
    "logfile": "\/media\/USBdrive\/ncdata\/nextcloud.log",
    "loglevel": "2",
    "log_type": "file",
    "theme": "",
    "mail_sendmailmode": "smtp",
    "ldapIgnoreNamingRules": false,
    "ldapProviderFactory": "OCA\\User_LDAP\\LDAPProviderFactory",
    "mail_smtpauth": 1,
    "mail_smtpsecure": "ssl",
    "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
    "mail_smtpport": "465",
    "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
    "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
    "app_install_overwrite": [
        "files_external_gdrive",
        "files_external_onedrive",
        "occweb"
    ]
}

**Are you using external storage, if yes which one:** local/smb/sftp/...
local

**Are you using encryption:** 
no

### Server log (data/nextcloud.log)

{"reqId":"Xl9W3VbEE-rJGT6vQLe3LgAACRY","level":3,"time":"2020-03-04T07:21:01+00:00","remoteAddr":"10.0.0.33","user":"<username>","app":"remote","method":"MOVE","url":"/remote.php/dav/files/<username>/Dokumente/Neues%20Textdokument2.md","message":{"Exception":"Error","Message":"Call to a member function getPath() on null","Code":0,"Trace":[{"file":"/var/www/nextcloud/apps/workflowengine/lib/AppInfo/Application.php","line":114,"function":"onEvent","class":"OCA\\WorkflowScript\\Operation","type":"->","args":["*** sensitive parameter replaced ***","*** sensitive parameter replaced ***",{"__class__":"OCA\\WorkflowEngine\\Service\\RuleMatcher"}]},{"file":"/var/www/nextcloud/3rdparty/symfony/event-dispatcher/EventDispatcher.php","line":247,"function":"OCA\\WorkflowEngine\\AppInfo\\{closure}","class":"OCA\\WorkflowEngine\\AppInfo\\Application","type":"->","args":["*** sensitive parameters replaced ***"]},{"file":"/var/www/nextcloud/3rdparty/symfony/event-dispatcher/EventDispatcher.php","line":73,"function":"callListeners","class":"Symfony\\Component\\EventDispatcher\\EventDispatcher","type":"->","args":[[{"__class__":"Closure"}],"*** sensitive parameter replaced ***","*** sensitive parameter replaced ***"]},{"file":"/var/www/nextcloud/lib/private/EventDispatcher/EventDispatcher.php","line":80,"function":"dispatch","class":"Symfony\\Component\\EventDispatcher\\EventDispatcher","type":"->","args":["*** sensitive parameter replaced ***","*** sensitive parameter replaced ***"]},{"file":"/var/www/nextcloud/lib/private/EventDispatcher/SymfonyAdapter.php","line":63,"function":"dispatch","class":"OC\\EventDispatcher\\EventDispatcher","type":"->","args":["*** sensitive parameter replaced ***","*** sensitive parameter replaced ***"]},{"file":"/var/www/nextcloud/lib/private/Files/Node/HookConnector.php","line":147,"function":"dispatch","class":"OC\\EventDispatcher\\SymfonyAdapter","type":"->","args":["*** sensitive parameter replaced ***","*** sensitive parameter replaced ***"]},{"file":"/var/www/nextcloud/lib/private/legacy/hook.php","line":111,"function":"postRename","class":"OC\\Files\\Node\\HookConnector","type":"->","args":[{"oldpath":"/Dokumente/Neues Textdokument2.md","newpath":"/Dokumente/Neues Textdokument.md"}]},{"file":"/var/www/nextcloud/lib/private/Files/View.php","line":849,"function":"emit","class":"OC_Hook","type":"::","args":["OC_Filesystem","post_rename",{"oldpath":"/Dokumente/Neues Textdokument2.md","newpath":"/Dokumente/Neues Textdokument.md"}]},{"file":"/var/www/nextcloud/apps/dav/lib/Connector/Sabre/Node.php","line":143,"function":"rename","class":"OC\\Files\\View","type":"->","args":["/Dokumente/Neues Textdokument2.md","/Dokumente/Neues Textdokument.md"]},{"file":"/var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Tree.php","line":151,"function":"setName","class":"OCA\\DAV\\Connector\\Sabre\\Node","type":"->","args":["Neues Textdokument.md"]},{"file":"/var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/CorePlugin.php","line":642,"function":"move","class":"Sabre\\DAV\\Tree","type":"->","args":["files/<username>/Dokumente/Neues Textdokument2.md","files/<username>/Dokumente/Neues Textdokument.md"]},{"function":"httpMove","class":"Sabre\\DAV\\CorePlugin","type":"->","args":[{"absoluteUrl":"https://<url>/remote.php/dav/files/<username>/Dokumente/Neues%20Textdokument2.md","__class__":"Sabre\\HTTP\\Request"},{"__class__":"Sabre\\HTTP\\Response"}]},{"file":"/var/www/nextcloud/3rdparty/sabre/event/lib/EventEmitterTrait.php","line":105,"function":"call_user_func_array","args":[[{"__class__":"Sabre\\DAV\\CorePlugin"},"httpMove"],[{"absoluteUrl":"https://<url>/remote.php/dav/files/<username>/Dokumente/Neues%20Textdokument2.md","__class__":"Sabre\\HTTP\\Request"},{"__class__":"Sabre\\HTTP\\Response"}]]},{"file":"/var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php","line":479,"function":"emit","class":"Sabre\\Event\\EventEmitter","type":"->","args":["method:MOVE",[{"absoluteUrl":"https://<url>/remote.php/dav/files/<username>/Dokumente/Neues%20Textdokument2.md","__class__":"Sabre\\HTTP\\Request"},{"__class__":"Sabre\\HTTP\\Response"}]]},{"file":"/var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php","line":254,"function":"invokeMethod","class":"Sabre\\DAV\\Server","type":"->","args":[{"absoluteUrl":"https://<url>/remote.php/dav/files/<username>/Dokumente/Neues%20Textdokument2.md","__class__":"Sabre\\HTTP\\Request"},{"__class__":"Sabre\\HTTP\\Response"}]},{"file":"/var/www/nextcloud/apps/dav/lib/Server.php","line":319,"function":"exec","class":"Sabre\\DAV\\Server","type":"->","args":[]},{"file":"/var/www/nextcloud/apps/dav/appinfo/v2/remote.php","line":35,"function":"exec","class":"OCA\\DAV\\Server","type":"->","args":[]},{"file":"/var/www/nextcloud/remote.php","line":165,"args":["/var/www/nextcloud/apps/dav/appinfo/v2/remote.php"],"function":"require_once"}],"File":"/var/www/nextcloud/apps/workflow_script/lib/Operation.php","Line":203,"CustomMessage":"--"},"userAgent":"Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:73.0) Gecko/20100101 Firefox/73.0","version":"18.0.1.3"}

**Comment by NewRedsquare** [comment]
I have the same issue... opened 29 days ago... hope this will be fixed soon !

**Comment by jacotec** [comment]
Same here, it's annoying. Is there any relation to config or active apps known?

**Comment by martingwb** [comment]
> I've played around a bit and found I had a Workflow Script activated (just for testing). Deleting this solves the issue.
Sorry, this does not "solve" the issue, it does "avoid" the issue.

> Do you have some Workflow -> Scripts active? Seems to be related.
Yes, I can confirm that.

> In case both of you have an external script in the workflow, maybe move/copy the issue to the repo of this app: https://github.com/nextcloud/workflow_script
Isn't that exactly where we are right here?

**Comment by jacotec** [comment]
> Sorry, this does not "solve" the issue, it does "avoid" the issue.

Absolutely!

> > In case both of you have an external script in the workflow, maybe move/copy the issue to the repo of this app: https://github.com/nextcloud/workflow_script
> 
> Isn't that exactly where we are right here?

OMG ... Shame on me. I had a server core Github tab open and mixed both. Must be too much sun today :( Sorry for that!

**Comment by R0Wi** [comment]
Hi all, i think i was able to fix the issue. If you would like to test it you can check out my branch [here](https://github.com/R0Wi/workflow_script/tree/bugfix/%2342_getPath_null). Let me know your results :-)

**Comment by martingwb** [comment]
@R0Wi - tested rename and move - result: as expected

**Comment by blizzz** [comment]
@R0Wi thanks for taking care – since you have a fix, turn it into a PR :)
