### ISSUE TITLE
External script does not work in shared folders

### ISSUE THREAD

**Issue by andreasdeschka** [nextcloud/workflow_script#48]
## Steps to reproduce
A shares a folder with B. B uploads a file to the folder and the script gets executed.

### Expected behaviour
The script gets executed, %i and %f should not be empty.

### Actual behaviour
The script gets executed, %i is filled but %f is empty.
When the script is executed by a user in a folder he owns, it works fine.

## Workflow Script app

**Workflow Script app version:** (see apps admin page: `/index.php/settings/apps`)
workflow_script: 1.3.1

**Nextcloud version:** 
18.0.3

**Comment by andreasdeschka** [comment]
I added in Launcher.php:
\OC_Util::setupFS($user);

Then it works.

$user can be passed as an argument like $path.

This should also solve the issue #38

**Comment by jakobroehrl** [comment]
Can confirm this problem. 
@andreasdeschka 
Could you create a pull request with your solution? That would be awesome! 👍

**Comment by microfx** [comment]
> I added in `Launcher.php`:
> `\OC_Util::setupFS($user);`

How? Just adding it somewhere? At the end?

**Comment by jakobroehrl** [comment]
@nickvergessen @blizzz 
Can you help me solving this issue?

**Comment by k1l1** [comment]
Can confirm this bug. The Path of the Folder creator is used, since the path provided by "external workflow" does not exist on the drive. The full path of the file of user A is required.

**Comment by k1l1** [comment]
I created a (temporary) fix #64
