### ISSUE TITLE
Automatically Convert video on files in folder

### ISSUE THREAD

**Issue by ifuchs** [nextcloud/workflow_script#57]
How could I use this workflow to run the NC Convert Video app on any file that is uploaded to a folder drop? If running the Convert Video app is not possible, is there an equivalent script that uses ffmpeg?

**Comment by n3storm** [comment]
You can create you own script and put in on the server to be run by this module

**Comment by blizzz** [comment]
As this seems to be a setup issue I would like to ask you to raise your question in the forums: https://help.nextcloud.com

If you wish support with setup issues from Nextcloud GmbH we offer this as part of the Nextcloud subscription. Learn more about this at https://nextcloud.com/enterprise/
