### ISSUE TITLE
Does the input field accept regular expressions?

### ISSUE THREAD

**Issue by hj-beckers** [nextcloud/workflow_script#58]
version workflow external scripts 1.4.0, nextcloud server 19.0.2

in
'if file created and filename is " "', does the input field accept regular expressions? Only when I enter a static name eg. "testfile.txt" my script gets executed. Entering "test*.txt" oder "test.*.txt" doesn't match for "testfile.txt". Is a special syntax needed?

**Comment by blizzz** [comment]
select "matches" instead of "is", then you can use regex expressions. This is provided by the worklfowengine, part of Nextcloud server.

**Comment by hj-beckers** [comment]
The only selection possible is (in the german version) "ist/ist nicht" translated "is/is not" ? I can enter a value, would I use "entspricht"?  Can I find the german values somewhere in the source?

**Comment by hj-beckers** [comment]
found apps/workflowengine/l10n/de_DE.js: "entspricht/entspricht nicht". But why do these values not show up in the dropdown menu? I'm using chromium Version 84.0.4147.135 (openSUSE Build) (64-Bit).

**Comment by hj-beckers** [comment]
Further tests: I can enter different values, but I cannot save the rule. The input field only accepts "ist/ist nicht".

**Comment by blizzz** [comment]
Ah, we have some hidden magic here. Perhaps should make it more obvious… anyway, the comparator changes to matches automatically, when you start your check with a slash ("/").

**Comment by hj-beckers** [comment]
Entering a "/" at the beginning of the input field restricts the selection to "match/does not match" or the german "entspricht/entspricht nicht". But now the rule "if file created and file name matches /test.*.txt"  switches the save button to "This configuration is invalid" (The given regular expression is invalid). Where can I find the allowed syntax?

**Comment by blizzz** [comment]
@hj-beckers the pattern has to be encapsulated in slashes. If you remove the leading slash, it switches back to is/is not.

**Comment by hj-beckers** [comment]
It works. Thank you for the prompt reaction, Closing the "bug".
