### ISSUE TITLE
Script execution terminated when using systemd timer as cron job scheduler

### ISSUE THREAD

**Issue by dbw9580** [nextcloud/workflow_script#67]
## Steps to reproduce
1. Use systemd as the cron job scheduler, as per instructions in https://docs.nextcloud.com/server/19/admin_manual/configuration_server/background_jobs_configuration.html#systemd
2. Set up a workflow script that requires quite some time to run, e.g. `sleep 10; echo "finished" > /tmp/flow_output`
3. Trigger the cron job, e.g. from command line `systemctl start nextcloudcron.service`

### Expected behaviour
The workflow script finishes successfully.

### Actual behaviour
Nothing happens. No output in `/tmp/flow_output`.

## Workflow Script app

1.4.0

## Workaround

Because systemd defaults to kill all the processes of a service unit as soon as the main process has exited, once the php process exits, the child process where the flow script is running will be killed, too. Making systemd only kill the main process but leaving all child processes intact works around this problem ([ref: systemd.kill](https://www.freedesktop.org/software/systemd/man/systemd.kill.html#KillMode=)). 

Append `KillMode=process` to the `nextcloudcron.service` file:

```
[Unit]
Description=Nextcloud cron.php job

[Service]
User=www-data
ExecStart=/usr/bin/php -f /var/www/nextcloud/cron.php
KillMode=process
```

I'm not sure if this issue should be filed here, or under the server repo, or the documentation repo. I feel that posting it here may save someone who runs into the same problem hours of researching.

**Comment by MorrisJobke** [comment]
cc @blizzz

**Comment by kesselb** [comment]
https://github.com/nextcloud/workflow_script/blob/145ae8f237d0f1d6efa14634a5ee5d9c64376aec/lib/BackgroundJobs/Launcher.php#L69-L76

The command is executed as subshell on purpose. So the suggest change to the documentation makes sense to me.

**Comment by blizzz** [comment]
@dbw9580 thanks for the report, analysis and the documentation PR. Closing hence it is merged.
