### ISSUE TITLE
Workflow not being run

### ISSUE THREAD

**Issue by kgw4it** [nextcloud/workflow_script#7]
## Steps to reproduce
1. Install a fresh nextcloud instance (i.e. Docker 15.0.0-apache) and the workflow_script app
2. Setup a workflow rule group without any rules (and therefore matching all files being uploaded or updated or renamed) and set a command (i.e. 'echo "%e %i %a %o %n %f %x" >> /tmp/1.log')
3. Upload a file

### Expected behaviour
I would expect that the workflow is run and that a file **/tmp/1.log** is created.

### Actual behaviour
Nothing happens.
I tried to debug it a bit and for me it looks like the hooks (i.e. postCreate) are not being called.

## Workflow Script app

**Workflow Script app version:** 1.0.0

## Server configuration

**Operating system**: Ubuntu

**Web server:** Apache

**Database:** MySQL

**PHP version:** 7.2.13

**Nextcloud Version:** 15.0.0

**Where did you install Nextcloud from:** Docker 15.0.0-apache

**Signing status:** 

No errors have been found.

**List of activated apps:**

<details>
```
Enabled:
  - accessibility: 1.1.0
  - activity: 2.8.2
  - cloud_federation_api: 0.1.0
  - comments: 1.5.0
  - dav: 1.8.0
  - federatedfilesharing: 1.5.0
  - federation: 1.5.0
  - files: 1.10.0
  - files_pdfviewer: 1.4.0
  - files_sharing: 1.7.0
  - files_texteditor: 2.7.0
  - files_trashbin: 1.5.0
  - files_versions: 1.8.0
  - files_videoplayer: 1.4.0
  - firstrunwizard: 2.4.0
  - gallery: 18.2.0
  - logreader: 2.0.0
  - lookup_server_connector: 1.3.0
  - nextcloud_announcements: 1.4.0
  - notifications: 2.3.0
  - oauth2: 1.3.0
  - password_policy: 1.5.0
  - provisioning_api: 1.5.0
  - serverinfo: 1.5.0
  - sharebymail: 1.5.0
  - support: 1.0.0
  - survey_client: 1.3.0
  - systemtags: 1.5.0
  - theming: 1.6.0
  - twofactor_backupcodes: 1.4.1
  - updatenotification: 1.5.0
  - workflow_script: 1.0.0
  - workflowengine: 1.5.0
Disabled:
  - admin_audit
  - encryption
  - files_external
  - user_external
  - user_ldap
```
</details>

**Nextcloud configuration:**

<details>
```
{
    "system": {
        "htaccess.RewriteBase": "\/",
        "memcache.local": "\\OC\\Memcache\\APCu",
        "apps_paths": [
            {
                "path": "\/var\/www\/html\/apps",
                "url": "\/apps",
                "writable": false
            },
            {
                "path": "\/var\/www\/html\/custom_apps",
                "url": "\/custom_apps",
                "writable": true
            }
        ],
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "***REMOVED SENSITIVE VALUE***"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "15.0.0.10",
        "overwrite.cli.url": "https:\/\/cloudstage.w4it.at",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "mysql.utf8mb4": true,
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "trusted_proxies": "***REMOVED SENSITIVE VALUE***",
        "filelocking.enabled": true,
        "memcache.distributed": "\\OC\\Memcache\\Redis",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "***REMOVED SENSITIVE VALUE***",
            "port": "***REMOVED SENSITIVE VALUE***",
            "timeout": "***REMOVED SENSITIVE VALUE***",
            "dbindex": "***REMOVED SENSITIVE VALUE***"
        },
        "mail_smtpmode": "smtp",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "***REMOVED SENSITIVE VALUE***",
        "ldapIgnoreNamingRules": false,
        "ldapProviderFactory": "\\OCA\\User_LDAP\\LDAPProviderFactory",
        "loglevel": 2,
        "maintenance": false,
        "theme": "",
    }
}
```
</details>

**Are you using external storage, if yes which one:** no

**Are you using encryption:** no

### Server log (data/nextcloud.log)
<details>
```
EMPTY
```
</details>

**Comment by blizzz** [comment]
A cronjob should be registered, the scripts are executed with a background job.

**Comment by kgw4it** [comment]
Hey. Thanks for the quick reply. I checked the `oc_jobs` table and I never saw an entry there that looked like it's related to the workflow_script app.
As far as I understand, here https://github.com/nextcloud/workflow_script/blob/master/lib/AppInfo/Application.php#L73 listeners are registered to execute in case a file gets added or updated or renamed. Therefore for every file I upload I would expect that this line https://github.com/nextcloud/workflow_script/blob/master/lib/AppInfo/Application.php#L44 is executed. But my debugging showed that this code only gets executed for `previews` that are generated after a file was uploaded, but never for the file itself.
That's why I assumed that something is wrong with the hooks..

Just to confirm setting up a single rule group without any rules and the following command `echo "%e %i %a %o %n %f %x" >> /tmp/1.log`, should in fact add a line to the `/tmp/1.log` file every time a file gets uploaded, right?

**Comment by blizzz** [comment]
I share your expectations.

> Just to confirm setting up a single rule group without any rules and the following command echo "%e %i %a %o %n %f %x" >> /tmp/1.log, should in fact add a line to the /tmp/1.log file every time a file gets uploaded, right?

Yes, however on systemd-bases systems /tmp/ is usually jailed on a service subdirectory on /tmp, e.g. `/tmp/systemd-private-3f055192b6d41929609a65440ab0fbc-httpd.service-95Rog0/tmp`

**Comment by idistech** [comment]
Im seeing the same behaviour here - Ubuntu 16.04 - Ive placed the script and the output to /var/tmp and /var/www and /var/log/nextcloud but getting the same issue - is there somewhere were we can see an error  log to you think ?

**Comment by blizzz** [comment]
@idistech it must also have permission to write to those directories. if something is logged, then in the nextcloud log file within the data directory.

**Comment by chasx003** [comment]
I'm having the same issues.  I don't see any logs that even make me think the script is trying to run.  Just trying to echo to a location that www-data owns.

Seems this person is also having the same issues https://help.nextcloud.com/t/help-with-workflow-external-scripts-app/47937

**Comment by wiswedel** [comment]
(almost) same for me. Script is only being triggerd on creation of a new text file from the web UI. Uploads, renamings, folder creation etc. aren't triggering anything.

**Comment by it25fg** [comment]
Same here. The only event that causes a script to be executed is content modification. No exceptions in the log.
Besides, even content modification does not always trigger anything, for instance if the ruleset contains rules mentioning tags. I have created https://github.com/nextcloud/server/issues/14401 for this as it seems to be a problem in the workflow framework.

**Comment by blizzz** [comment]
I gave it a try as well, and yes there seem to be some issue, alas specific to checks. It worked for me when i restricted the user to be part of a group. This worked. What didn't:
mimetype – was interpreted as "application/octet-strem" instead of "plain/text"
tag – could not resolve the path to file ids

What are your failing rules?

**Comment by it25fg** [comment]
Nice to meet you @blizzz 

> What are your failing rules?

First, I tested a simple rule 'file has tag' that never fired because of an exception in the workflow framework. Then, I found one rule that worked: this was a file name regexp. Later on, I noticed that even this was only fired on **modification** from the **web frontend**. Not on upload, and not on modification on a watched directory in a desktop client. That's all I've seen so far, I'll continue testing.

**Comment by blizzz** [comment]
Heyo @it25fg  :) 

thanks for the input, I'll investigate that, too!

**Comment by wiswedel** [comment]
My rules were file name regexp and _no rule at all_ which usually fires for every object everytime something happens (at least that's how files_automatictagging reacts)

**Comment by blizzz** [comment]
I have the fix: #10. It's rather embarrassing and i have no explanation how it slipped in first place :-/

**Comment by blizzz** [comment]
i published the 1.0.1 with the fix

**Comment by it25fg** [comment]
Hopefully this won't open the issue again... Simply want to confirm that my flavor of the issue (workflow not being run on upload or on modification via sync client) really has gone away. Many thanks @blizzz & keep up the good work!

**Comment by blizzz** [comment]
Thanks @it25fg for confirming and the nice words :)

**Comment by orangeswim** [comment]
hello, i see that this issue is already closed, but i'm running into the same issue. 
Workflow external scripts 1.1.0
NextCloud 16.0.1

**Comment by blizzz** [comment]
@orangeswim please open a new bug report with all requested details
