### ISSUE TITLE
Error while processing multiple files

### ISSUE THREAD

**Issue by chr-sy** [nextcloud/workflow_script#72]
## Steps to reproduce
1. Install workflow_script App
2. Setup new flow (Admin section) to run /full/path/process_file.sh %n
3. Add file to fulfill flow condition

process_file.sh:
#!/bin/sh
JPGFILE=$1
NCDATA="/DATEN/nextcloud_data"
FILE="$NCDATA$1"
BASE="${FILE%.*}"
FILEPATH="${JPGFILE%/*}"
TARGET="$BASE.pdf"
ocrmypdf -l deu+eng --image-dpi 300 $FILE $TARGET && rm $FILE
php /var/www/cloud.ds-ing.net/nextcloud/occ files:scan --path=$FILEPATH

### Expected behaviour
process_file.sh should be run for each of the new files, convert the file into pdf (including OCR) and re-scan the respective directory so that the newly created pdf is visible within nextcloud.

### Actual behaviour
For single files, everything works as expected. If multiple files are written between 2 cron.php calls, the script does not work (at least if commands are involved which need a considerable time to finish).

I can't tell if the error is caused by bad configuation or a bug in one of the tools...

Running cron.php manually reveals the following error:

 Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib/python3.6/multiprocessing/managers.py", line 177, in accepter
    t.start()
  File "/usr/lib/python3.6/threading.py", line 846, in start
    _start_new_thread(self._bootstrap, ())
RuntimeError: can't start new thread

Traceback (most recent call last):
  File "/usr/bin/ocrmypdf", line 11, in <module>
    load_entry_point('ocrmypdf==6.1.2', 'console_scripts', 'ocrmypdf')()
  File "/usr/lib/python3/dist-packages/ocrmypdf/__main__.py", line 816, in run_pipeline
    logging_factory, __name__, logger_args)
  File "/usr/lib/python3/dist-packages/ruffus/proxy_logger.py", line 343, in make_shared_logger_and_proxy
    logger_proxy = manager.setup_logger(logger_name, args)
  File "/usr/lib/python3.6/multiprocessing/managers.py", line 662, in temp
    token, exp = self._create(typeid, *args, **kwds)
  File "/usr/lib/python3.6/multiprocessing/managers.py", line 554, in _create
    conn = self._Client(self._address, authkey=self._authkey)
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 493, in Client
    answer_challenge(c, authkey)
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 732, in answer_challenge
    message = connection.recv_bytes(256)         # reject large message
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 216, in recv_bytes
    buf = self._recv_bytes(maxlength)
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 407, in _recv_bytes
    buf = self._recv(4)
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 383, in _recv
    raise EOFError
EOFError
Traceback (most recent call last):
  File "/usr/bin/ocrmypdf", line 11, in <module>
    load_entry_point('ocrmypdf==6.1.2', 'console_scripts', 'ocrmypdf')()
  File "/usr/lib/python3/dist-packages/ocrmypdf/__main__.py", line 816, in run_pipeline
    logging_factory, __name__, logger_args)
  File "/usr/lib/python3/dist-packages/ruffus/proxy_logger.py", line 343, in make_shared_logger_and_proxy
    logger_proxy = manager.setup_logger(logger_name, args)
  File "/usr/lib/python3.6/multiprocessing/managers.py", line 662, in temp
    token, exp = self._create(typeid, *args, **kwds)
  File "/usr/lib/python3.6/multiprocessing/managers.py", line 554, in _create
    conn = self._Client(self._address, authkey=self._authkey)
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 487, in Client
    c = SocketClient(address)
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 614, in SocketClient
    s.connect(address)
FileNotFoundError: [Errno 2] No such file or directory

## Workflow Script app

**Workflow Script app version:** (see apps admin page: `/index.php/settings/apps`)
1.5.0

## Server configuration

**Operating system**: Ubuntu/RedHat/...
Linux 4.15.0 #1 SMP Tue Jun 9 12:58:54 MSK 2020 x86_64 (Ubuntu 18.04)

**Web server:** Apache/Nginx
Apache/2.4.29 (Ubuntu) (apache2handler)

**Database:** MySQL/Maria/SQLite/PostgreSQL
mysql 10.1.47

**PHP version:**
7.4.13
Modules loaded: Core, date, libxml, openssl, pcre, zlib, filter, hash, Reflection, SPL, session, standard, sodium, apache2handler, mysqlnd, PDO, xml, apcu, bcmath, calendar, ctype, curl, dom, mbstring, FFI, fileinfo, ftp, gd, gettext, gmp, iconv, imagick, intl, json, exif, mysqli, pdo_mysql, apc, posix, readline, shmop, SimpleXML, sockets, sysvmsg, sysvsem, sysvshm, tokenizer, xmlreader, xmlwriter, xsl, zip, Phar, Zend OPcache

**Nextcloud Version:** (see admin page)
20.0.4 - 20.0.4.0

**Where did you install Nextcloud from:**
https://download.nextcloud.com

**Signing status:**
Array
(
)

**List of activated apps:**
Enabled:
 - accessibility: 1.6.0
 - audioplayer: 3.0.0
 - calendar: 2.1.3
 - cloud_federation_api: 1.3.0
 - comments: 1.10.0
 - contacts: 3.4.3
 - contactsinteraction: 1.1.0
 - dashboard: 7.0.0
 - dav: 1.16.2
 - deck: 1.2.3
 - documentserver_community: 0.1.8
 - duplicatefinder: 0.0.4
 - federatedfilesharing: 1.10.2
 - federation: 1.10.1
 - files: 1.15.0
 - files_antivirus: 3.1.1
 - files_external: 1.11.1
 - files_fulltextsearch: 20.0.0
 - files_fulltextsearch_tesseract: 20.0.1
 - files_pdfviewer: 2.0.1
 - files_rightclick: 0.17.0
 - files_sharing: 1.12.1
 - files_texteditor: 2.14.0
 - files_trashbin: 1.10.1
 - files_versions: 1.13.0
 - files_videoplayer: 1.9.0
 - firstrunwizard: 2.9.0
 - fulltextsearch: 20.0.0
 - fulltextsearch_elasticsearch: 20.0.0
 - groupfolders: 8.2.0
 - issuetemplate: 0.7.0
 - logreader: 2.5.0
 - lookup_server_connector: 1.8.0
 - maps: 0.1.8
 - nextcloud_announcements: 1.9.0
 - notes: 4.0.2
 - notifications: 2.8.0
 - oauth2: 1.8.0
 - onlyoffice: 6.2.0
 - password_policy: 1.10.1
 - photos: 1.2.1
 - polls: 1.6.3
 - privacy: 1.4.0
 - provisioning_api: 1.10.0
 - quota_warning: 1.9.1
 - serverinfo: 1.10.0
 - settings: 1.2.0
 - side_menu: 1.21.0
 - spreed: 10.0.5
 - support: 1.3.0
 - systemtags: 1.10.0
 - tasks: 0.13.6
 - theming: 1.11.0
 - twofactor_backupcodes: 1.9.0
 - updatenotification: 1.10.0
 - viewer: 1.4.0
 - workflow_ocr: 1.20.1
 - workflow_script: 1.5.0
 - workflowengine: 2.2.0
Disabled:
 - activity
 - admin_audit
 - apporder
 - bruteforcesettings
 - encryption
 - epubreader
 - flow_notifications
 - recommendations
 - sharebymail
 - survey_client
 - text
 - user_ldap
 - user_status
 - weather_status

**Nextcloud configuration:**
{
    "instanceid": "***REMOVED SENSITIVE VALUE***",
    "passwordsalt": "***REMOVED SENSITIVE VALUE***",
    "secret": "***REMOVED SENSITIVE VALUE***",
    "trusted_domains": [
        "localhost",
        "***server.url***"
    ],
    "datadirectory": "***REMOVED SENSITIVE VALUE***",
    "dbtype": "mysql",
    "version": "20.0.4.0",
    "dbname": "***REMOVED SENSITIVE VALUE***",
    "dbhost": "***REMOVED SENSITIVE VALUE***",
    "dbport": "",
    "dbtableprefix": "oc_",
    "dbuser": "***REMOVED SENSITIVE VALUE***",
    "dbpassword": "***REMOVED SENSITIVE VALUE***",
    "installed": true,
    "maintenance": false,
    "mysql.utf8mb4": true,
    "memcache.local": "\\OC\\Memcache\\APCu",
    "mail_from_address": "***REMOVED SENSITIVE VALUE***",
    "mail_smtpmode": "smtp",
    "mail_sendmailmode": "smtp",
    "mail_domain": "***REMOVED SENSITIVE VALUE***",
    "mail_smtpauthtype": "PLAIN",
    "mail_smtpauth": 1,
    "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
    "mail_smtpport": "465",
    "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
    "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
    "mail_smtpsecure": "ssl",
    "overwrite.cli.url": "https:\/\/***server.url***",
    "theme": "",
    "loglevel": 2,
    "logfile": "\/var\/log\/nextcloud.log",
    "logtimezone": "Europe\/Berlin",
    "auth.bruteforce.protection.enabled": false,
    "app_install_overwrite": [
        "ocr"
    ]
}

**Are you using external storage, if yes which one:** none

**Are you using encryption:** no

**Comment by blizzz** [comment]
@chr-sy that's rather an issue with  the script (or the commands its doing) rather than talk. You fail with a message by python, stating ` RuntimeError: can't start new thread`. That's out of Nextcloud, out of workflow_script and our control.

If the commands you are running afterwards for some reason cannot do the similar tasks in the same time, you need to queue them somehow, to ensure one is processed after the other.
