### ISSUE TITLE
Cant run python scripts

### ISSUE THREAD

**Issue by MarVinSto** [nextcloud/workflow_script#77]
I want to run a python script called from a bash script, which is called from workflow script.
I verify in my for this purpose created logfiles, that the bash scripts gets triggered, but stops when the python script should start.
When I start the script by manually, the scripts and subscripts run as expected.

Also, I could not enable the direct call of a Python script through workflow.

Is it possible to call python scripts at all?

## Steps to reproduce
1. create python script which is executable from www-data
2. create bash script which is executable from www-data and call python script in it.
3. check functionality by starting manually

### Expected behaviour
execute python script called from bash script

### Actual behaviour
bash script runs up to the point, where the python script starts and then stops.

## Workflow Script app

**Workflow Script app version:** (see apps admin page: `/index.php/settings/apps`)
1.5.1
## Server configuration

**Operating system**: 
manjaro

**Web server:** 
Nginx

**Database:** 
Maria

**PHP version:**
7.4.14

**Nextcloud Version:** (see admin page)
20.0.5

**Where did you install Nextcloud from:**
pacman

**Signing status:**

```
No errors have been found.
```

**List of activated apps:**

<details>
```
Enabled:
  - accessibility: 1.6.0
  - activity: 2.13.4
  - admin_audit: 1.10.0
  - analytics: 3.2.0
  - breezedark: 20.0.3
  - bruteforcesettings: 2.0.1
  - calendar: 2.1.3
  - cloud_federation_api: 1.3.0
  - contacts: 3.4.3
  - contactsinteraction: 1.1.0
  - dashboard: 7.0.0
  - dav: 1.16.2
  - deck: 1.2.3
  - documentserver_community: 0.1.8
  - federatedfilesharing: 1.10.2
  - federation: 1.10.1
  - files: 1.15.0
  - files_fulltextsearch: 20.0.0
  - files_fulltextsearch_tesseract: 20.0.1
  - files_markdown: 2.3.1
  - files_pdfviewer: 2.0.1
  - files_rightclick: 0.17.0
  - files_sharing: 1.12.2
  - files_trashbin: 1.10.1
  - files_versions: 1.13.0
  - files_videoplayer: 1.9.0
  - firstrunwizard: 2.9.0
  - flow_notifications: 1.0.3
  - fulltextsearch: 20.0.0
  - fulltextsearch_elasticsearch: 20.0.0
  - groupfolders: 8.2.0
  - impersonate: 1.7.0
  - logreader: 2.5.0
  - lookup_server_connector: 1.8.0
  - nextcloud_announcements: 1.9.0
  - notes: 4.0.2
  - notifications: 2.8.0
  - oauth2: 1.8.0
  - onlyoffice: 6.2.0
  - password_policy: 1.10.1
  - photos: 1.2.3
  - privacy: 1.4.0
  - provisioning_api: 1.10.0
  - ransomware_protection: 1.8.0
  - serverinfo: 1.10.0
  - settings: 1.2.0
  - sharebymail: 1.10.0
  - spreed: 10.0.5
  - support: 1.3.0
  - survey_client: 1.8.0
  - systemtags: 1.10.0
  - tasks: 0.13.6
  - text: 3.1.0
  - theming: 1.11.0
  - twofactor_backupcodes: 1.9.0
  - updatenotification: 1.10.0
  - viewer: 1.4.0
  - weather_status: 1.0.0
  - workflow_script: 1.5.1
  - workflowengine: 2.2.0
Disabled:
  - camerarawpreviews
  - circles
  - comments
  - encryption
  - end_to_end_encryption
  - files_external
  - integration_github
  - integration_gitlab
  - integration_moodle
  - mail
  - printer
  - recommendations
  - socialsharing_email
  - talk_simple_poll
  - user_ldap
  - user_status
  - workflow_ocr

```
</details>

**Nextcloud configuration:**

<details>
```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder

or

Insert your config.php content here
Make sure to remove all sensitive content such as passwords. (e.g. database password, passwordsalt, secret, smtp password, …)
```
</details>

**Are you using external storage, if yes which one:**
no

**Are you using encryption:**
no

### Server log (data/nextcloud.log)
<details>
```
Insert your server log here
```
</details>

**Comment by frederikmoellers** [comment]
I've set up a script with a Python Shebang (`#!/usr/bin/env python3`) and configured workflow_script to call that one directly. It executes without problems.
Maybe there's a problem calling the script in the first place? How do you call the python script? Do you maybe need to specify the absolute path (to the script and/or the python executable)?
Maybe you can debug the bash script using `set -e` and piping stderr to a log file.

**Comment by MarVinSto** [comment]
I'm really sorry, but I revised my .sh and .py and it looks like I had a few errors in my script.
With the revised script everything works fine.

Thanks for your help anyway!

PS: Is it possible that workflow_scripts doesnt execute, if the files which should trigger the script, is in an groupfolder?

**Comment by frederikmoellers** [comment]
> PS: Is it possible that workflow_scripts doesnt execute, if the files which should trigger the script, is in an groupfolder?

I haven't had a look at the app's code, so this is only a guess:
I could imagine that changes in a group folder don't (necessarily) generate activity events for the user who has this workflow configured and that this keeps the script from being executed.

**Comment by intervisionlord** [comment]
Hello and sorry for necroposting ;) Is it possible to run python script from workflow without using bash?

**Comment by frederikmoellers** [comment]
Yes, you can call Python scripts directly. See [this comment](https://github.com/nextcloud/workflow_script/issues/77#issuecomment-779204054).
