### ISSUE TITLE
Getting "no such file or directory" for created file

### ISSUE THREAD

**Issue by tetebueno** [nextcloud/workflow_script#85]
## Steps to reproduce
1. Configure new flow with the following parameters:
  * When: file created
  * File MIME type matches (custom) "video/mp4"
  * Run script: `head -c 8 "%f"`
2. Activate new flow.
3. Upload an .mp4 file (whether using desktop client or web interface).

### Expected behaviour
Should see `head` result (first eight bytes) in NC's log.

### Actual behaviour
Getting `head: cannot open "'/data-folder/user-name/files/file-name.mp4'" for reading: No such file or directory` error message on logs when job is run.

## Workflow Script app

**Workflow Script app version:** 1.6.0

## Server configuration

**Operating system**: Linux 5.4.0-65-generic #73~18.04.1-Ubuntu SMP PREEMPT Tue Jan 19 09:45:51 UTC 2021 x86_64

**Web server:** Apache/2.4.38 (Debian) (apache2handler)

**Database:** MariaDB 10.4.18

**PHP version:** 7.4.15
Modules loaded: Core, date, libxml, openssl, pcre, sqlite3, zlib, ctype, curl, dom, fileinfo, filter, ftp, hash, iconv, json, mbstring, SPL, PDO, session, posix, Reflection, standard, SimpleXML, pdo_sqlite, Phar, tokenizer, xml, xmlreader, xmlwriter, mysqlnd, apache2handler, apcu, bcmath, exif, gd, gmp, imagick, intl, ldap, memcached, pcntl, pdo_mysql, pdo_pgsql, redis, sodium, zip, Zend OPcache

**Nextcloud Version:** 21.0.0 - 21.0.0.18

**Where did you install Nextcloud from:** Docker Hub

**Signing status:** Array
(
)

```
No errors have been found.
```

**List of activated apps:**

<details>

```
Enabled:
  - accessibility: 1.7.0
  - activity: 2.14.3
  - breezedark: 21.0.2
  - cloud_federation_api: 1.4.0
  - comments: 1.11.0
  - contactsinteraction: 1.2.0
  - dashboard: 7.1.0
  - dav: 1.17.1
  - federatedfilesharing: 1.11.0
  - federation: 1.11.0
  - files: 1.16.0
  - files_pdfviewer: 2.1.0
  - files_rightclick: 1.0.0
  - files_sharing: 1.13.1
  - files_trashbin: 1.11.0
  - files_versions: 1.14.0
  - files_videoplayer: 1.10.0
  - firstrunwizard: 2.10.0
  - geoblocker: 0.4.6
  - issuetemplate: 0.7.0
  - logreader: 2.6.0
  - lookup_server_connector: 1.9.0
  - maps: 0.1.8
  - metadata: 0.13.0
  - nextcloud_announcements: 1.10.0
  - notifications: 2.9.0
  - oauth2: 1.9.0
  - password_policy: 1.11.0
  - photos: 1.3.0
  - previewgenerator: 3.1.1
  - privacy: 1.5.0
  - provisioning_api: 1.11.0
  - recommendations: 1.0.0
  - serverinfo: 1.11.0
  - settings: 1.3.0
  - sharebymail: 1.11.0
  - support: 1.4.0
  - survey_client: 1.9.0
  - systemtags: 1.11.0
  - text: 3.2.0
  - theming: 1.12.0
  - twofactor_backupcodes: 1.10.0
  - twofactor_gateway: 0.17.0
  - updatenotification: 1.11.0
  - user_status: 1.1.1
  - viewer: 1.5.0
  - weather_status: 1.1.0
  - workflow_script: 1.6.0
  - workflowengine: 2.3.0
Disabled:
  - admin_audit
  - encryption
  - files_external
  - user_ldap
```

</details>

**Nextcloud configuration:**

<details>

```
{
    "system": {
        "htaccess.RewriteBase": "\/",
        "memcache.local": "\\OC\\Memcache\\APCu",
        "apps_paths": [
            {
                "path": "\/var\/www\/html\/apps",
                "url": "\/apps",
                "writable": false
            },
            {
                "path": "\/var\/www\/html\/custom_apps",
                "url": "\/custom_apps",
                "writable": true
            }
        ],
        "overwritehost": "alfajordepollo.com.ar",
        "overwriteprotocol": "https",
        "overwritewebroot": "cloud",
        "trusted_proxies": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "localhost"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "21.0.0.18",
        "overwrite.cli.url": "https:\/\/localhostcloud",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "mysql.utf8mb4": true,
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "maintenance": false,
        "updater.secret": "***REMOVED SENSITIVE VALUE***",
        "loglevel": 2,
        "app_install_overwrite": [
            "twofactor_gateway",
            "issuetemplate"
        ]
    }
}
```

</details>

**Are you using external storage, if yes which one:** local

**Are you using encryption:** no

### Server log (data/nextcloud.log)
<details>

```

```

</details>

**Comment by trueMiskin** [comment]
Same error on NC 20.0.9.

**Comment by blizzz** [comment]
@tetebueno @trueMiskin can you verify that the logged path is indeed correct?

**Comment by trueMiskin** [comment]
@blizz

```shell
www-data@dc53691ceb2e:~/html$ php cron.php 
ls: cannot access "'/var/www/html/data/admin/files/autoeditor_2021-03-29 13-59-47.mkv'": No such file or directory
www-data@dc53691ceb2e:~/html$ ls -l '/var/www/html/data/admin/files/autoeditor_2021-03-29 13-59-47.mkv'
-rw-r--r-- 1 www-data www-data 16886039 Mar 29 12:01 '/var/www/html/data/admin/files/autoeditor_2021-03-29 13-59-47.mkv'
```

**Comment by blizz** [comment]
@blizzz

    On Monday, April 19, 2021, 7:39:53 AM MDT, Michal Kodad ***@***.***> wrote:  
 
 


@blizz
***@***.***:~/html$ php cron.php 
ls: cannot access "'/var/www/html/data/admin/files/autoeditor_2021-03-29 13-59-47.mkv'": No such file or directory
***@***.***:~/html$ ls -l '/var/www/html/data/admin/files/autoeditor_2021-03-29 13-59-47.mkv'
-rw-r--r-- 1 www-data www-data 16886039 Mar 29 12:01 '/var/www/html/data/admin/files/autoeditor_2021-03-29 13-59-47.mkv'

**Comment by tetebueno** [comment]
Ok, I've seemed to figure it out. My issue was related to quoting the file name placeholder.

I added the following flow:

* File created
* File MIME type is Custom mimetype "text/plain"
* Script: `cp "%f" /tmp`

Then I added a text file (using desktop sync client):

```
$ echo "hi" > file.txt
$ cp file.txt Nextcloud/
```

When file was created I force run cron inside the NC Docker container:

```
# runuser -u www-data -- php cron.php && ls /tmp/file.txt
cp: cannot stat "'/data-folder/user-name/files/file.txt'": No such file or directory
```

Then, I modified the script of the flow with the following script:

* Script: `cp %f /tmp`

I deleted the txt file and added it again the same way.

And forced cron again:

```
# runuser -u www-data -- php cron.php && ls -rt /tmp/file.txt
file.txt
```

I'll be closing the bug, since this shows the app works fine. In fact, I've already been able to configure the app with more complex scripts.

Hope it helps.
