### ISSUE TITLE
Q: NC21 in Docker - Flow Script not Activated

### ISSUE THREAD

**Issue by LinuksGuru** [nextcloud/workflow_script#87]
Hi!

I have NC 21 installed in Docker (on Debian Buster), and currently writing custom flow script, it should create a PDF from a given file. Unfortunately, due to some limits of built-in standard features I have to design my own script.
I added custom flow script, based on Tag assignment: “ok” tag assigned to a file - run script.

`/opt/CalcSheet2pdf.sh -f %n -o %o`

Script copied inside Docker container:

`docker cp CalcSheet2pdf.sh xxxxxxxxxx:/opt`

Right now (for debug purposes) this script simply outputs line with date to the log file, and does NOTHING else. I can login into docker container, and run this script from within the Bash shell, it outputs log file in /var/log (where I can navigate within docker). So script’s syntax is OK, its “rx” permissions are for everyone.
However, when I assign tag “ok” in NC Web to a file, I can’t find any trace of this script ever luanched. No logs in /var/log in Docker container, and no logs in /var/cloud_data within Docker’s host OS (where NC log file lives).

`cat nextcloud.log | grep Calc`

results nothing.

Any idea what went wrong?
Thanks in advance.

**Comment by LinuksGuru** [comment]
I copied this script (inside NC Docker) into 2 addtional dirs
/bin
/var/www/html (where NC lives)

No changes, doesn't work,  flow.log is empty.

**Comment by LinuksGuru** [comment]
I changed rule, File rename -> name matches -> \ok\i
Script still not invoked. NextCloud sees script, since if it doesn't exists, it throws error when trying to save settings.

**Comment by blizzz** [comment]
Are background jobs running there?

**Comment by LinuksGuru** [comment]
Yes, background jobs are running. BTW, I'm was able to (partially) solve this problem. Script **IS** activated **only** if it's located inside NC data directory. Any location outside NC data dir, e.g. /opt, /usr/bin, whatever, and no success, and no error message anywhere. 

Additionally, NC 21 Docker/Apache (from Docker hub) comes with a security mechanism that prevents custom flow script to run anything from /usr/bin, for example, making it utterly useless. I added www-data to "users" group, no changes. Using sudo would be too awkward and complex because of too many options required in /etc/sudoers.

How to fix this? Thanks in advance.

**Comment by blizzz** [comment]
> Additionally, NC 21 Docker/Apache (from Docker hub) comes with a security mechanism that prevents custom flow script to run anything from /usr/bin, for example, making it utterly useless. I added www-data to "users" group, no changes. Using sudo would be too awkward and complex because of too many options required in /etc/sudoers.
> 
> How to fix this? Thanks in advance.

As this seems to be a setup issue I would like to ask you to raise your question in the forums: https://help.nextcloud.com
