### ISSUE TITLE
Nextcloud 21.0.4 and upload feature

### ISSUE THREAD

**Issue by danjde** [nextcloud/workflow_script#98]
## Steps to reproduce
1. installing Workflow external scripts 1.5.1 into Nextcloud 21.0.4

### Expected behaviour
1. Find "file is uploaded" condition
2. Find "and is located"
3. Find "Pick a folder"

### Actual behaviour
No "file is uploaded" condition is shown

## Workflow Script app

**Workflow Script app version:** 1.5.1

## Server configuration

**Operating system**: Debian Stretch

**Web server:** Apache 2.4.25

**Database:** Maria 10.1.48

**PHP version:** 7.3.24

**Nextcloud Version:** 21.0.4

**Where did you install Nextcloud from:** from official nextcloud download webpage

```
Login as admin user into your Nextcloud and access
http://example.com/index.php/settings/integrity/failed

No errors have been found.
```

**Are you using external storage, if yes which one:** No

**Are you using encryption:** no

_MY QUESTION:_

_Installing Workflow external scripts from github solve the issue?_

Thanks

**Comment by radoeka** [comment]
> Installing Workflow external scripts from github solve the issue?

Do you still have this issue?

Is it OK to close this issue?

**Comment by blizzz** [comment]
As there is no feedback since a while I will close this ticket. If this is still happening please feel free to reopen.
