### ISSUE TITLE
Scan output created files to the nextcloud database

### ISSUE THREAD

**Issue by tk0233** [nextcloud/workflow_script#99]
## Steps to reproduce
1. create a flow closely following the documentation example which creates a new output file
2. script puts the new output file into the nextcloud directory structure
3. file cannot be seen within nextcloud unless manual occ files:scan is run

### Expected behaviour
Feature to scan output files or documentation recommendation (or warning against) this use case.

### Actual behaviour
Handling this use case is currently entirely up to the user. This may be the right behaviour, a note in the documentation would be appreciated.

## Workflow Script app

Workflow Script app version: 1.7.0

## Server configuration

**Operating system**: Ubuntu 20.04

**Web server:** Apache2

**Database:** Maria

**PHP version:** 7.3

**Nextcloud Version:** 22.1.1

**Where did you install Nextcloud from:** Followed docs install

**Comment by blizzz** [comment]
This is expected behaviour, unless you put the new  files into the directory via WebDAV API.
